config/routes.rb
Rails.application.routes.draw do

  resources :links
  resources :users
  resources :votes

  root 'links#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :votes

  validates :body, presence: true
  validates :title, presence: true

  after_create :create_owner_vote

  def positive_votes
    self.votes.where('positive > 0').count
  end

  def negative_votes
    self.votes.where('negative > 0').count
  end

  def aggregate_votes
    self.positive_votes - self.negative_votes
  end

  def create_owner_vote
    Vote.create!(link_id: self.id, user_id: self.user_id, positive: 1, negative: 0)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes
  has_many :links
  
  validates :user_name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link

  validates :positive, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 1 }
  validates :negative, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 1
  }

  validates :user_id, uniqueness: {
    scope: :link_id,
    message: "Cannot vote for the same link more than once."
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.select("links.*, SUM(votes.positive - votes.negative) as aggregate_votes")
                 .joins(:votes)
                 .group("links.id")
                 .order("aggregate_votes DESC")
                 .page(params[:page])
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.create(title: params[:link][:title],
                        body: params[:link][:body],
                        user_id: params[:link][:user_id])
    redirect_to link_path(@link.id)
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      redirect_to @link
    else
      render 'edit'
    end
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    redirect_to :back
  end

  private
    def link_params
      params.require(:link).permit(:title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_name: params[:user][:user_name],
                        first_name: params[:user][:first_name],
                        last_name: params[:user][:last_name],
                        email: params[:user][:last_name])
    redirect_to user_path(@user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to :users
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def show
  end

  def create
    #pull the creates out of the if statement, do an if/then where the result is psitive or negative.
    if params[:positive] == "yes"
      Vote.create!(link_id: params[:link_id].to_i, positive: 1, negative: 0, user_id: 50)
      redirect_to :back
    elsif params[:positive] == "no"
      Vote.create!(link_id: params[:link_id].to_i, positive: 0, negative: 1, user_id: 50)
      redirect_to :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IronReddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
      <ul>
        <li><%= link_to "Home", links_path%></li>
        <li><%= link_to "Create a link!", new_link_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "New User", new_user_path %></li>
      </ul>
    </nav>
<% if params[:controller] == "links" && params[:action] == "index" %>
  <div id="clicky-button" class='waves-effect waves-light btn'> Top Link </div>
<% end %>
<div class='container'>
<%= yield %>
</div>

<% if @links %>
  <%= paginate @links %>
<% end %>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
      <div>
        <div>
          <%= f.label :title %>
          <%= f.text_field :title, class: 'input-field title', placeholder: "You won't believe what happens next!" %>
        </div>

        <div>
          <%= f.label :body %>
          <% if params[:action] == "edit" %>
            <%= f.text_field :body, class: 'input-field body', placeholder: "www.clickbait.com", disabled: true %>
          <% else %>
            <%= f.text_field :body, class: 'input-field body', placeholder: "www.clickbait.com" %>
          <% end %>
        </div>

        <div>
          <%= f.label :user_id%>
          <% if params[:action] == "edit" %>
            <%= f.collection_select(:user_id, User.all, :id, :user_name, {}, disabled: true) %>
          <% else %>
            <%= f.collection_select(:user_id, User.all, :id, :user_name) %>
          <% end %>
        </div>
        <div>
          <%= f.submit %>
        </div>
      </div>
<% end %>

app/views/links/_form_vote.html.erb
<%= form_for(@link) do |f| %>
<% link.votes.positive += 1 %>
<%= f.submit "Like" %>

<% end %>

app/views/links/edit.html.erb
<h3 id="count-me"> Link you wish to edit </h3>

<%= render partial: 'form' %>

app/views/links/index.html.erb
<h1 id="count-me"> All those links </h1>

<% @links.each do |link| %>
  <p class="main-text"> <a class="main-links" href='<%=link.body%>'> <%= link.title %></a> | Aggregate: <%= link.aggregate_votes %> </p>
  <!-- put into the model to detect if a vote has been cast -->
  <% if link.votes.where('user_id = 50') == [] %>
    <%= button_to 'Like', votes_path(link_id: link.id, positive: 'yes'), method: :post, form_class: "waves-effect waves-light btn" %>
    <%= button_to 'Dislike', votes_path(link_id: link.id, positive: 'no'), method: :post, form_class: "waves-effect waves-light btn" %>
  <% end %>
  <%= link_to "Edit", { controller: "links", action: "edit", id: link.id }, class: "waves-effect waves-light btn" %>
  <%= button_to "delete", {:controller => :links,
        :action => 'destroy', :id => link.id }, :method => :delete, form_class: "waves-effect waves-light btn" %>
<% end %>

app/views/links/new.html.erb
<h3 id="count-me"> Create a new link </h3>
<%= render partial: 'form' %>

app/views/links/show.html.erb
<h3 id="count-me"> This is the link </h3>

<p> <a class="main-links" href='<%=@link.body%>'> <%= @link.title %></a> | <%= @link.aggregate_votes %></p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
      <div>
        <div>
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: 'input-field title', placeholder: "PowerUser5000!" %>
        </div>

        <div>
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'input-field body', placeholder: "John/Jane" %>
        </div>

        <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'input-field body', placeholder: "Doe" %>
        </div>

        <%= f.label :email %>
        <%= f.text_field :email, class: 'input-field body', placeholder: "you@u.yourself" %>
        </div>
        <div>
          <%= f.submit %>
        </div>
      </div>
<% end %>

app/views/users/index.html.erb
<h1 id="count-me"> All those users </h1>

<% @users.each do |user| %>
  <p class="users-text"> <a class="main-links" href='users/<%=user.id%>'> <%= user.user_name %></a> | <%= user.first_name %> | <%= user.last_name %></p>
<% end %>

app/views/users/new.html.erb
<h3 id="count-me"> Create a new user </h3>
<%= render partial: 'form' %>

app/views/users/show.html.erb
<h2 id="count-me"> That user <%= @user.user_name %> </h2>

<p class="users-text"> <a class="main-links"><%= @user.user_name %></a> | <%= @user.first_name %>| <%= @user.last_name %></p>
<%= button_to "delete", {:controller => :users, :action => 'destroy', :id => @user.id }, :method => :delete, form_class: "waves-effect waves-light btn" %>
<% @user.links.each do |link| %>
<p class="main-text"> <a class="main-links" href='<%=link.body%>'> <%= link.title %></a> | Aggregate: <%= link.aggregate_votes %> </p>
<% end %>